version: '3.8'

services:
  opentofu-deployer:
    build: .
    ports:
      - "${PORT:-8080}:${PORT:-80}"
    environment:
      - PORT=${PORT:-80}
      - TEMP_DIR=/usercontent
      - DEPLOYMENTS_DIR=/data
    volumes:
      - usercontent:/usercontent
      - deployments:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-80}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  usercontent:
    driver: local
  deployments:
    driver: local